ci:
  skip:
    - "compose-pyproject"
    - "pytest-fast-only"
    - "pytest-slow-only"
    - "pyright"
  autoupdate_schedule: "quarterly"

repos:
  - repo: "meta"
    hooks:
      - id: "check-hooks-apply"
      - id: "check-useless-excludes"
  - repo: "local"
    hooks:
      # * -------------------------------------------------------------------------- * #
      # * Changes below should persist in significant template updates.

      # * -------------------------------------------------------------------------- * #
      # * Changes below may be lost in significant template updates.
      - id: "compose-pyproject"
        name: "compose-pyproject"
        fail_fast: true
        pass_filenames: false
        language: "system"
        entry: "pwsh -Command python .tools/scripts/compose_pyproject.py"
        files: |
          (?x)^(
            pyproject.toml
            |requirements.txt
            |.tools/pyproject.toml
          )$
      - id: "pyright"
        name: "pyright"
        fail_fast: true
        pass_filenames: false
        language: "system"
        entry: "pwsh .tools/scripts/Invoke-Pyright.ps1"
        files: |
          (?x)^(
            src/.*
            |tests/.*
            |pyproject.toml
            |requirements.txt
            |.tools/(
              pyproject.toml
              |requirements/.*
            )
          )$
      - id: "pytest-fast-only"
        name: "pytest-fast-only"
        fail_fast: true
        verbose: true
        pass_filenames: false
        language: "system"
        entry: |
          pwsh -Command "pytest -m 'not slow' --suppress-no-test-exit-code"
        files: |
          (?x)^(
            pyproject.toml
            |requirements.txt
            |.tools/(
              pyproject.toml
              |requirements/.*
            )
          )$
      - id: "pytest-slow-only"
        name: "pytest-slow-only"
        fail_fast: true
        verbose: true
        pass_filenames: false
        language: "system"
        entry: "pwsh -Command pytest -m slow"
        files: |
          (?x)^(
            src/.*
            |tests/.*
          )$

  # * ------------------------------------------------------------------------------ * #
  # * Changes below should persist in significant template updates.

  # * ------------------------------------------------------------------------------ * #
  # * Changes below may be lost in significant template updates.

  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "v4.4.0"
    hooks:
      - id: "end-of-file-fixer"
      - id: "trailing-whitespace"
  - repo: "https://github.com/DavidAnson/markdownlint-cli2"
    rev: "v0.7.1"
    hooks:
      - id: "markdownlint-cli2-fix"
  - repo: "https://github.com/psf/black"
    rev: "23.3.0"
    hooks:
      - id: "black"
  - repo: "https://github.com/charliermarsh/ruff-pre-commit"
    rev: "v0.0.263"
    hooks:
      - id: "ruff"
  - repo: "https://github.com/srstevenson/nb-clean"
    rev: "2.4.0"
    hooks:
      - id: "nb-clean"
        args:
          - "--remove-empty-cells"
          - "--preserve-cell-metadata"
          - "tags"
          - "slideshow"
          - "special"
          - "--"
  - repo: "https://github.com/asottile/blacken-docs"
    rev: "1.13.0"
    hooks:
      - id: "blacken-docs"
        additional_dependencies: ["black==23.3.0"]
  - repo: "https://github.com/nbQA-dev/nbQA"
    rev: "1.7.0"
    hooks:
      - id: "nbqa-black"
        additional_dependencies: ["black==23.3.0"]
      - id: "nbqa-ruff"
        additional_dependencies: ["ruff==0.0.263"]
