exclude: |
  (?x)^(
    \.copier-answers\.yml
    |changelog/towncrier_template\.md\.jinja
  )$
ci:
  skip:
    - "sync"
    - "fawltydeps-src"
    - "fawltydeps-dev"
    - "pytest-fast-only"
  autoupdate_schedule: "quarterly"
default_install_hook_types:
  - "pre-commit"
  - "post-checkout" # sync
repos:
  - repo: "meta"
    hooks:
      # ? Enable this to ensure each hook runs against at least one file
      # - id: "check-hooks-apply"
      - id: "check-useless-excludes"
  - repo: "local"
    hooks:
      - id: "sync"
        name: "sync"
        stages:
          - "pre-commit"
          - "post-checkout"
        pass_filenames: false
        language: "system"
        entry: |
          pwsh -Command "./Invoke-Uv.ps1 -Sync -Update"
      - id: "fawltydeps-src"
        name: "fawltydeps-src"
        pass_filenames: false
        language: "system"
        entry: |
          pwsh -Command "./Invoke-Uv.ps1 fawltydeps --config-file pyproject.toml"
        files: |
          (?x)^(
            pyproject\.toml
            |src/.*
          )$
      - id: "fawltydeps-dev"
        name: "fawltydeps-dev"
        pass_filenames: false
        language: "system"
        entry: |
          pwsh -Command "./Invoke-Uv.ps1 fawltydeps --config-file packages/_dev/pyproject.toml"
        files: |
          (?x)^(
            packages/_dev/.*
            |docs/.*
            |tests/.*
          )$
      - id: "pytest-fast-only"
        name: "pytest-fast-only"
        pass_filenames: false
        language: "system"
        entry: |
          pwsh -Command "./Invoke-Uv.ps1 pytest -m 'not slow'"
        files: |
          (?x)^(
            .*/pyproject\.toml
            |docs/.*
            |requirements/.*
            |scripts/.*
            |src/.*
            |tests/.*
          )$
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "v4.6.0"
    hooks:
      - id: "end-of-file-fixer"
      - id: "trailing-whitespace"
  - repo: "https://github.com/DavidAnson/markdownlint-cli2"
    rev: "v0.13.0"
    hooks:
      - id: "markdownlint-cli2"
  - repo: "https://github.com/srstevenson/nb-clean"
    rev: "3.3.0"
    hooks:
      - id: "nb-clean"
        args:
          - "--remove-empty-cells"
          - "--preserve-notebook-metadata"
          - "--preserve-cell-metadata"
          - "tags"
          - "--"
        files: |
          (?x)^(
            docs/.*
            |src/.*
            |tests/.*
          )$
  - repo: "https://github.com/rbubley/mirrors-prettier"
    rev: "v3.3.3"
    hooks:
      - id: "prettier"
  - repo: https://github.com/ComPWA/taplo-pre-commit
    rev: "v0.9.3"
    hooks:
      - id: "taplo-format"
  - repo: "https://github.com/charliermarsh/ruff-pre-commit"
    rev: "v0.5.1"
    hooks:
      - id: "ruff"
        args: ["--extend-fixable", "PIE790"]
        types_or: ["python", "pyi", "jupyter"]
      - id: "ruff-format"
        types_or: ["python", "pyi", "jupyter"]
