blank_issues_enabled: false
contact_links:
  - name: "Ask a question"
    url: "https://github.com/blakeNaccarato/copier-python/discussions/new?category=q-a"
    about: "Ask for help. Please search related Q&As in case your question has been asked before."
