name: main

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  flake8:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9
      - run: |
          pip install -U pip
          pip install -r requirements.txt
          copier gh:blakeNaccarato/copier-python . -r HEAD -f
          pip install -r requirements_cicd.txt
          flit install
      - run: flake8

  pyright:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9
      - run: |
          pip install -U pip
          pip install -r requirements.txt
          copier gh:blakeNaccarato/copier-python . -r HEAD -f
          pip install -r requirements_cicd.txt
          flit install
      - uses: actions/setup-node@v2.4.0
        with:
          node-version: "14"
      - run: npm install
      - run: node_modules/.bin/pyright

  pytest-cov:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9
      - run: |
          pip install -U pip
          pip install -r requirements.txt
          copier gh:blakeNaccarato/copier-python . -r HEAD -f
          pip install -r requirements_cicd.txt
          flit install
      - run: pytest --cov
      - uses: codecov/codecov-action@v2.0.2
