name: bump

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: [requirements.txt]

jobs:
  bump:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version:
      - run: pip install -U pip setuptools wheel -r .tools/requirements/requirements_cicd.txt
      - run: python .tools/scripts/bump_pyproject.py
      - uses: stefanzweifel/git-auto-commit-action@v4.14.1
        with:
          commit_message: Bump `pyproject.toml` dependencies
