# Run static analysis, tests, and sync
name: "ci"
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: True
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: ["main"]
defaults:
  run:
    shell: "pwsh"
env:
  UV_CACHE_DIR: ".cache/uv-cache"
  UV_SYSTEM_PYTHON: "true"
jobs:
  sync:
    strategy:
      matrix:
        runner: ["ubuntu-22.04"]
        python: ["3.10"]
    runs-on: "${{ matrix.runner }}"
    steps:
      - uses: "actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332" # v4.1.7
        with:
          submodules: True
      - uses: "actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d" # v5.1.0
        with:
          python-version: "${{ matrix.python }}"
      - run: "scripts/Sync-Py.ps1"
      - uses: "actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808" # v4.3.3
        with:
          name: "lock"
          path: "lock.json"
      - uses: "actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9" # v4.0.2
        with:
          path: "${{ env.UV_CACHE_DIR }}"
          key: "uv-${{ matrix.runner }}-${{ matrix.python }}-${{ hashFiles('lock.json') }}"
  build-docs:
    needs: "sync"
    strategy:
      matrix:
        runner: ["ubuntu-22.04"]
        python: ["3.10"]
    runs-on: "${{ matrix.runner }}"
    steps:
      - uses: "actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332" # v4.1.7
        with:
          submodules: True
      - uses: "actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e" # v4.1.7
        with:
          name: "lock"
      - uses: "actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9" # v4.0.2
        with:
          path: "${{ env.UV_CACHE_DIR }}"
          key: "uv-${{ matrix.runner }}-${{ matrix.python }}-${{ hashFiles('lock.json') }}"
      - uses: "actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d" # v5.1.0
        with:
          python-version: "${{ matrix.python }}"
      - run: "scripts/Sync-Py.ps1"
      - run: ". scripts/Initialize-Shell.ps1; sphinx-build -EaT docs _site"
      - uses: "actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa" # v3.0.1
  deploy-docs:
    if: github.event_name != 'pull_request'
    needs: "build-docs"
    permissions:
      pages: "write"
      id-token: "write"
    strategy:
      matrix:
        runner: ["ubuntu-22.04"]
        python: ["3.10"]
    environment:
      name: "github-pages"
      url: "${{ steps.deployment.outputs.page_url }}"
    runs-on: "${{ matrix.runner }}"
    steps:
      - id: "deployment"
        uses: "actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e" # v4.0.5
  ruff:
    needs: "sync"
    strategy:
      matrix:
        runner: ["ubuntu-22.04"]
        python: ["3.10"]
    runs-on: "${{ matrix.runner }}"
    steps:
      - uses: "actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332" # v4.1.7
        with:
          submodules: True
      - uses: "actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e" # v4.1.7
        with:
          name: "lock"
      - uses: "actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9" # v4.0.2
        with:
          path: "${{ env.UV_CACHE_DIR }}"
          key: "uv-${{ matrix.runner }}-${{ matrix.python }}-${{ hashFiles('lock.json') }}"
      - uses: "actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d" # v5.1.0
        with:
          python-version: "${{ matrix.python }}"
      - run: "scripts/Sync-Py.ps1"
      - run: ". scripts/Initialize-Shell.ps1; ruff check --no-fix --output-format github ."
  fawltydeps:
    needs: "sync"
    strategy:
      matrix:
        runner: ["ubuntu-22.04"]
        python: ["3.10"]
    runs-on: "${{ matrix.runner }}"
    steps:
      - uses: "actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332" # v4.1.7
        with:
          submodules: True
      - uses: "actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e" # v4.1.7
        with:
          name: "lock"
      - uses: "actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9" # v4.0.2
        with:
          path: "${{ env.UV_CACHE_DIR }}"
          key: "uv-${{ matrix.runner }}-${{ matrix.python }}-${{ hashFiles('lock.json') }}"
      - uses: "actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d" # v5.1.0
        with:
          python-version: "${{ matrix.python }}"
      - run: "scripts/Sync-Py.ps1"
      - run: ". scripts/Initialize-Shell.ps1; fawltydeps"
  pyright:
    needs: "sync"
    strategy:
      matrix:
        runner: ["ubuntu-22.04"]
        python: ["3.10"]
    runs-on: "${{ matrix.runner }}"
    steps:
      - uses: "actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332" # v4.1.7
        with:
          submodules: True
      - uses: "actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e" # v4.1.7
        with:
          name: "lock"
      - uses: "actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9" # v4.0.2
        with:
          path: "${{ env.UV_CACHE_DIR }}"
          key: "uv-${{ matrix.runner }}-${{ matrix.python }}-${{ hashFiles('lock.json') }}"
      - uses: "actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d" # v5.1.0
        with:
          python-version: "${{ matrix.python }}"
      - run: "scripts/Sync-Py.ps1"
      - run: ". scripts/Initialize-Shell.ps1; pyright"
  test:
    needs: "sync"
    strategy:
      matrix:
        runner:
          - "macos-13"
          - "ubuntu-22.04"
          - "windows-2022"
        python:
          - "3.10"
          - "3.11"
          - "3.12"
    runs-on: "${{ matrix.runner }}"
    steps:
      - uses: "actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332" # v4.1.7
        with:
          submodules: True
      - uses: "actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e" # v4.1.7
        with:
          name: "lock"
      - uses: "actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9" # v4.0.2
        with:
          path: "${{ env.UV_CACHE_DIR }}"
          key: "uv-${{ matrix.runner }}-${{ matrix.python }}-${{ hashFiles('lock.json') }}"
      - uses: "actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d" # v5.1.0
        with:
          python-version: "${{ matrix.python }}"
      - run: "scripts/Sync-Py.ps1 -Version '${{ matrix.python }}'"
      # ! https://github.com/pytest-dev/pytest-cov/issues/479#issuecomment-1247444988
      - run: ". scripts/Initialize-Shell.ps1; pytest --cov --cov-config pyproject.toml"
      - if: startsWith(matrix.runner, 'ubuntu') && matrix.python == '3.10'
        uses: "codecov/codecov-action@e28ff129e5465c2c0dcc6f003fc735cb6ae0c673" # v4.5.0
        env:
          CODECOV_TOKEN: "${{ secrets.CODECOV_TOKEN }}"
  lock:
    needs:
      - "ruff"
      - "fawltydeps"
      - "pyright"
      - "test"
    permissions:
      contents: "write"
    strategy:
      matrix:
        runner: ["ubuntu-22.04"]
        python: ["3.10"]
    runs-on: "${{ matrix.runner }}"
    steps:
      - uses: "actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332" # v4.1.7
        with:
          submodules: True
      - uses: "actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e" # v4.1.7
        with:
          name: "lock"
      - uses: "actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9" # v4.0.2
        with:
          path: "${{ env.UV_CACHE_DIR }}"
          key: "uv-${{ matrix.runner }}-${{ matrix.python }}-${{ hashFiles('lock.json') }}"
      - uses: "actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d" # v5.1.0
        with:
          python-version: "${{ matrix.python }}"
      - run: "scripts/Sync-Py.ps1"
      - uses: "stefanzweifel/git-auto-commit-action@8621497c8c39c72f3e2a999a26b4ca1b5058a842" # v5.0.1
        with:
          commit_message: "Sync and lock"
