# Simulate local contributor workflow sync process
name: "contrib"
on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/contrib.yml"
      - "scripts/Sync-Py.ps1"
      - "scripts/copier_python_tools/**"
      - "scripts/pyproject.toml"
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/contrib.yml"
      - "scripts/Sync-Py.ps1"
      - "scripts/copier_python_tools/**"
      - "scripts/pyproject.toml"
defaults:
  run:
    shell: "pwsh"
env:
  UV_CACHE_DIR: ".cache/uv"
  SYNC_PY_DISABLE_CI: True
jobs:
  no-spaces-in-path:
    strategy:
      matrix:
        runner:
          - "macos-13"
          - "ubuntu-22.04"
          - "windows-2022"
        python: ["3.11"]
    runs-on: "${{ matrix.runner }}"
    steps:
      - uses: "actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332" # v4.1.7
        with:
          submodules: True
      - uses: "actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9" # v4.0.2
        with:
          path: "${{ env.UV_CACHE_DIR }}"
          key: "uv-${{ matrix.runner }}-${{ matrix.python }}-${{ hashFiles('lock.json') }}"
      - uses: "actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f" # v5.1.1
        with:
          python-version: "${{ matrix.python }}"
      - run: "scripts/Sync-Py.ps1 -Version '3.11'"
  spaces-in-path:
    strategy:
      matrix:
        runner:
          - "macos-13"
          - "ubuntu-22.04"
          - "windows-2022"
        python: ["3.11"]
    runs-on: "${{ matrix.runner }}"
    steps:
      - run: "New-Item -ItemType Directory 'repo path with spaces'"
      - uses: "actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332" # v4.1.7
        with:
          submodules: True
          path: "repo path with spaces"
      - uses: "actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9" # v4.0.2
        with:
          path: "${{ env.UV_CACHE_DIR }}"
          key: "uv-${{ matrix.runner }}-${{ matrix.python }}-${{ hashFiles('repo path with spaces/lock.json') }}"
      - uses: "actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f" # v5.1.1
        with:
          python-version: "${{ matrix.python }}"
      - working-directory: "repo path with spaces"
        run: "scripts/Sync-Py.ps1 -Version '3.11'"
