# Simulate local contributor workflow sync process
name: "contrib"
on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/contrib.yml"
      - "scripts/Sync-Py.ps1"
      - "scripts/copier_python_tools/**"
      - "scripts/pyproject.toml"
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/contrib.yml"
      - "scripts/Sync-Py.ps1"
      - "scripts/copier_python_tools/**"
      - "scripts/pyproject.toml"
defaults:
  run:
    shell: "pwsh"
env:
  SYNC_PY_DISABLE_CI: true
jobs:
  no-spaces-in-path:
    strategy:
      matrix:
        runner:
          - "macos-13"
          - "ubuntu-22.04"
          - "windows-2022"
    runs-on: "${{ matrix.runner }}"
    steps:
      - uses: "actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11" # v4.1.1
        with:
          submodules: True
      - uses: "actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c" # v5.0.0
        with:
          python-version: "3.11"
      - run: "scripts/Sync-Py.ps1 -Lock -Version '3.11'"
  spaces-in-path:
    strategy:
      matrix:
        runner:
          - "macos-13"
          - "ubuntu-22.04"
          - "windows-2022"
    runs-on: "${{ matrix.runner }}"
    steps:
      - run: "New-Item -ItemType Directory 'repo path with spaces'"
      - uses: "actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11" # v4.1.1
        with:
          submodules: True
          path: "repo path with spaces"
      - uses: "actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c" # v5.0.0
        with:
          python-version: "3.11"
      - working-directory: "repo path with spaces"
        run: "scripts/Sync-Py.ps1 -Lock -Version '3.11'"
