# Test the upper-bound dependencies of the project
name: "high"
on:
  workflow_dispatch:
  schedule:
    - cron: "38 16 * * 4"
defaults:
  run:
    shell: "pwsh"
env:
  UV_CACHE_DIR: ".cache/uv-cache"
  UV_SYSTEM_PYTHON: "true"
jobs:
  test:
    strategy:
      matrix:
        runner:
          - "macos-13"
          - "macos-14"
          - "ubuntu-22.04"
          - "windows-2022"
        python:
          # - "3.10"  # `scripts` currently requires `tomllib`, which is > 3.10
          - "3.11"
          - "3.12"
          # - "3.13.0-alpha.5"  # https://github.com/PyO3/pyo3/issues/3555
    runs-on: "${{ matrix.runner }}"
    steps:
      - uses: "actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11" # v4.1.1
        with:
          submodules: True
      - uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: "${{ env.UV_CACHE_DIR }}"
          key: "uv-${{ matrix.runner }}"
      - uses: "actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d" # v5.1.0
        with:
          python-version: "${{ matrix.python }}"
      - run: "scripts/Sync-Py.ps1 -High -Version '${{ matrix.python }}'"
      - run: "pytest"
