name: "main"

on: ["workflow_dispatch", "push"]

jobs:
  changes:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "dorny/paths-filter@v2"
        id: "filter"
        with:
          filters: |
            precommit:
              - "bump/.pre-commit-config.yaml"
    outputs:
      precommit: "${{ steps.filter.outputs.precommit }}"
  bump_precommit:
    needs: "changes"
    if: "${{ needs.changes.outputs.precommit == 'true' }}"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-python@v4"
        with:
          python-version: "3.11"
      - run: "python bump/precommit.py"
      - uses: "stefanzweifel/git-auto-commit-action@v4"
        with:
          commit_message: "Update pre-commit config"
  test_installable:
    needs: "bump_precommit"
    if: "${{ !failure() }}"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-python@v4"
        with:
          python-version: "3.11"
      # Have to touch the file in a separate step before installing requirements
      - run: touch template/.tools/requirements/requirements_project.txt
      - run: touch template/.tools/requirements/requirements_docs.txt
      - run: |-
          pip install -U pip setuptools wheel
          pip install -r template/.tools/requirements/requirements_cicd.txt
      - run: "pip install -r 'template/.tools/requirements/{% if docs_engine == 'Jupyter Book' %}requirements_docs copy.txt{% endif %}'"
      - run: "pip install -r 'template/.tools/requirements/{% if docs_engine == 'MyST' %}requirements_docs.txt{% endif %}'"
