# Publish release
name: "release"
on:
  release:
    types: ["published"]
jobs:
  release:
    permissions:
      contents: "write"
      id-token: "write"
      attestations: "write"
    strategy:
      matrix:
        runner: ["ubuntu-22.04"]
        python: ["3.10"]
    runs-on: "${{ matrix.runner }}"
    environment:
      name: "release"
      url: "https://pypi.org/p/boilercv"
    steps:
      - uses: "actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332" # v4.1.7
      - uses: "actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d" # v5.1.0
        with:
          python-version: "${{ matrix.python }}"
      - run: "curl -LsSf https://astral.sh/uv/install.sh | sh"
      - run: "python -m pip install build; python -m build --installer uv"
      - uses: actions/attest-build-provenance@bdd51370e0416ac948727f861e03c2f05d32d78e # v1.3.2
        with:
          subject-path: "dist/**"
      - run: "gh release upload '${{ github.event.release.tag_name }}' dist/**"
        env:
          GITHUB_TOKEN: "${{ github.token }}"
      - uses: "pypa/gh-action-pypi-publish@ec4db0b4ddc65acdf4bff5fa45ac92d78b56bdf0" # v1.9.0
