# Publish release
name: "release"
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: True
on: ["release"]
defaults:
  run:
    shell: "pwsh"
jobs:
  release:
    permissions:
      contents: "write"
      id-token: "write"
      attestations: "write"
    runs-on: "ubuntu-22.04"
    environment:
      name: "release"
    steps:
      - uses: "actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332" # v4.1.7
      - uses: "astral-sh/setup-uv@9f1f1fece28798fe5e7ece00f4243abe886974b2" # v3.0.0
        with:
          version: "0.4.15"
          enable-cache: true
          cache-dependency-glob: |
            **/uv.lock
            .github/workflows/**
      - run: "./Invoke-Uv.ps1 -Build"
      - uses: actions/attest-build-provenance@5e9cb68e95676991667494a6a4e59b8a2f13e1d0 # v1.3.3
        with:
          subject-path: "dist/**"
  changerelease:
    needs: "release"
    permissions:
      contents: "write"
    uses: "./.github/workflows/changerelease.yml"
