# Publish release
name: "release"
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: True
on:
  release:
    types: ["published"]
defaults:
  run:
    shell: "pwsh"
jobs:
  release:
    permissions:
      contents: "write"
      id-token: "write"
      attestations: "write"
    strategy:
      matrix:
        runner: ["ubuntu-22.04"]
        python: ["3.10"]
    runs-on: "${{ matrix.runner }}"
    steps:
      - uses: "actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332" # v4.1.7
      - uses: "actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d" # v5.1.0
        with:
          python-version: "${{ matrix.python }}"
      - run: "scripts/Sync-Py.ps1 -Release"
      - run: ". scripts/Initialize-Shell.ps1; python -m build --installer uv"
      - uses: actions/attest-build-provenance@bdd51370e0416ac948727f861e03c2f05d32d78e # v1.3.2
        with:
          subject-path: "dist/**"
      - run: "gh release upload '${{ github.event.release.tag_name }}' dist/**"
        env:
          GITHUB_TOKEN: "${{ github.token }}"
  changerelease:
    needs: "release"
    permissions:
      contents: "write"
    uses: "./.github/workflows/changerelease.yml"
